name: ctrlz_counter
description: "A new Flutter project."
publish_to: 'none'
version: 0.9.0

environment:
  sdk: ^3.7.0

dependencies:
  bitsdojo_window: ^0.1.6
  drift: ^2.25.1
  drift_flutter: ^0.2.4
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_discord_rpc: ^1.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  win32: ^5.11.0
  window_manager: ^0.4.3
  provider: ^6.1.2
  elapsed_time_display: ^1.0.0
  hive_flutter: ^1.1.0
  dynamik_theme: ^0.1.4
  image_picker: ^1.1.2
  windows_single_instance: ^1.0.1
  palette_generator: ^0.3.3+6
  image: ^4.5.3
  confetti: ^0.8.0
  fluttertoast: ^8.2.12
  flutter_rounded_date_picker: ^3.0.4
  flutter_timer_countdown: ^1.0.7
  just_audio: ^0.9.46
  just_audio_windows: ^0.2.2
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.25.2
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/confetti.mp3
    - assets/sounds/yippie.mp3
    - assets/images/gatologo.png
    - assets/images/shary.png
    - assets/images/github.svg
