  name: "Nightly Build"

  on: 
    push

  jobs:
    build:
      name: Windows
      runs-on: windows-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v4

        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable
            cache: true
            cache-key: "flutter-:os:-:version:-:arch:"
            cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
        - run: flutter --version

        - name: Build for Windows
          run: flutter build windows --release
        
        - name: Compress build result
          uses: thedoctor0/zip-release@0.7.6
          with:
            path: build/windows/x64/runner/Release/*
            filename: nightly_build.zip
          
        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: Nightly
            path: nightly_build.zip